attribute = "fg.default"
keyword = "scale.red.3"
"keyword.directive" = "scale.red.3"          # -- preprocessor comments (#if in C)
namespace = "scale.orange.2"
punctuation = "fg.default"
"punctuation.delimiter" = "fg.default"
operator = "scale.red.3"
special = "scale.blue.1"
"variable.other.member" = "fg.default"
variable = "fg.default"
"variable.parameter" = "scale.orange.2"
"variable.builtin" = "scale.red.3"
type = "scale.orange.2"
"type.builtin" = "scale.blue.2"
constructor = "scale.purple.2"
function = "scale.purple.2"
"function.macro" = "scale.purple.2"
tag = "scale.green.1"
comment = "fg.muted"
constant = "scale.blue.2"
"constant.builtin" = "scale.blue.2"
string = "scale.blue.1"
"constant.numeric" = "scale.blue.2"
"constant.character.escape" = "scale.blue.2"
# used for lifetimes
label = "scale.red.3"

"markup.heading" = "scale.blue.2"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { modifiers = ["underlined"] }
"markup.link.text" = { fg = "scale.blue.1", modifiers = ["underlined"] }
"markup.raw" = "scale.blue.2"

"diff.plus" = "open.fg"
"diff.minus" = "closed.fg"
"diff.delta" = "attention.fg"

"ui.background" = { bg = "canvas.default" }
"ui.background.separator" = { fg = "fg.subtle" }
"ui.linenr" = { fg = "fg.subtle" }
"ui.linenr.selected" = { fg = "fg.default" }
"ui.statusline" = { fg = "fg.muted", bg = "scale.gray.7" }
"ui.statusline.active" = { fg = "fg.default", bg = "canvas.default", underline = { color = "scale.coral.3", style = "line" } }
"ui.statusline.normal" = { fg = "fg.default", bg = "accent.muted" }
"ui.statusline.insert" = { fg = "fg.default", bg = "attention.muted" }
"ui.statusline.select" = { fg = "fg.default", bg = "sponsors.muted" }
"ui.popup" = { bg = "scale.gray.8" }
"ui.popup.info" = { fg = "fg.default", bg = "canvas.overlay" }
"ui.window" = { fg = "border.default" }
"ui.help" = { fg = "fg.default", bg = "canvas.overlay" }

"ui.text" = { fg = "fg.muted" }
"ui.text.focus" = { fg = "fg.default" }
"ui.text.inactive" = "fg.subtle"
"ui.virtual" = { fg = "scale.gray.6" }

"ui.selection" = { bg = "scale.blue.8" }
"ui.selection.primary" = { bg = "scale.blue.7" }
"ui.cursor.match" = { fg = "attention.fg", modifiers = [
    "bold",
], underline = { style = "line" } }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.cursorline.primary" = { bg = "canvas.subtle" }

"ui.menu" = { fg = "fg.default", bg = "canvas.overlay" }
"ui.menu.selected" = { bg = "scale.gray.4" }
"ui.menu.scroll" = { fg = "scale.gray.5", bg = "canvas.overlay" }

"diagnostic.hint" = { underline = { color = "success.fg", style = "curl" } }
"diagnostic.info" = { underline = { color = "accent.fg", style = "curl" } }
"diagnostic.warning" = { underline = { color = "attention.fg", style = "curl" } }
"diagnostic.error" = { underline = { color = "danger.fg", style = "curl" } }

hint = "success.fg"
info = "accent.fg"
warning = "attention.fg"
error = "danger.fg"
